git_cache: git_cache
git_repo: https://github.com/electricbookworks/electric-book-gui.git
github_client: "SET github_client VAR FOR YOUR HOST"
github_secret: "SET github_secret VAR FOR YOUR HOST"
https: "s"